name: nested_navigation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  http: ^1.1.2
  provider: ^6.1.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  rename: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo/flex.jpg
    - assets/banner/flex_task_banner.png
    - assets/images/linkedin_logo.png
    - assets/images/github_logo.png
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/flex.jpg"

